name: BlueMenu
main: net.blueva.menu.Main
version: 1.0.0
api-version: 1.13
softdepend:
  - PlaceholderAPI

commands:
  bluemenu:
    description: Main command
    aliases:
      - bm
      - pluginmenu
      - custommenu