name: BlueMenu
main: net.blueva.menu.Main
version: ${project.version}
api-version: 1.21
softdepend:
  - PlaceholderAPI
  - ItemsAdder
  - Oraxen
  - Nexo

libraries:
  - "dev.dejvokep:boosted-yaml:${boosted-yaml.version}"
  - "net.kyori:adventure-api:${adventure.version}"
  - "net.kyori:adventure-platform-bukkit:${adventure-platform.version}"
  - "net.kyori:adventure-text-minimessage:${adventure.version}"
  - "com.zaxxer:HikariCP:${hikaricp.version}"
  - "com.mysql:mysql-connector-j:${mysql-connector.version}"

commands:
  bluemenu:
    description: Main command
    aliases:
      - bm
      - menu
      - menus

permissions:
  bluemenu.admin:
    description: Access to all BlueMenu commands
    default: op
  bluemenu.editor:
    description: Access to the web editor
    default: op
  bluemenu.open:
    description: Open menus for self or others
    default: true
